/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Stitch LocaBite Brand & System Tokens
        primary: "#ae2a00",
        "primary-container": "#d63d10",
        "on-primary": "#ffffff",
        "on-primary-container": "#fffbff",
        "inverse-primary": "#ffb4a1",
        "primary-fixed": "#ffdbd2",
        "primary-fixed-dim": "#ffb4a1",
        "on-primary-fixed": "#3c0800",
        "on-primary-fixed-variant": "#891f00",

        secondary: "#006c49",
        "secondary-container": "#6cf8bb",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#00714d",
        "secondary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",

        tertiary: "#825100",
        "tertiary-container": "#a36700",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",

        surface: "#f9f9ff",
        "surface-dim": "#d3daef",
        "surface-bright": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f3ff",
        "surface-container": "#e9edff",
        "surface-container-high": "#e1e8fd",
        "surface-container-highest": "#dce2f7",
        "surface-variant": "#dce2f7",
        "surface-tint": "#b32b00",

        "on-surface": "#141b2b",
        "on-surface-variant": "#5b403a",
        "inverse-surface": "#293040",
        "inverse-on-surface": "#edf0ff",
        outline: "#8f7068",
        "outline-variant": "#e4beb5",
        background: "#f9f9ff",
        "on-background": "#141b2b",

        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",

        // Design System Semantic Accents
        coral: {
          DEFAULT: "#F04F23",
          hover: "#E23E12",
          light: "#FFF1ED",
        },
        emerald: {
          DEFAULT: "#10B981",
          hover: "#059669",
          light: "#ECFDF5",
        },
        amber: {
          DEFAULT: "#F59E0B",
          hover: "#D97706",
          light: "#FEF3C7",
        }
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        gutter: "1rem",
        "gutter-sm": "0.75rem",
        "gutter-lg": "1.5rem",
        margin: "1rem",
        "margin-tablet": "1.5rem",
        "margin-desktop": "2.5rem",
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "system-ui", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "price-numeral": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-hero": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-hero-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
      },
      fontSize: {
        "display-hero": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "display-hero-mobile": ["30px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["26px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-sm": ["16px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-sm": ["11px", { lineHeight: "15px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "12px", letterSpacing: "0.04em", fontWeight: "700" }],
        "price-numeral": ["15px", { lineHeight: "18px", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
      boxShadow: {
        "level-1": "0 2px 8px -2px rgba(17, 24, 39, 0.05), 0 1px 3px 0 rgba(17, 24, 39, 0.03)",
        "level-2": "0 10px 24px -4px rgba(240, 79, 35, 0.12), 0 4px 10px -2px rgba(17, 24, 39, 0.06)",
        "level-3": "0 20px 35px -8px rgba(17, 24, 39, 0.16)",
      }
    },
  },
  plugins: [],
}
